#!/usr/bin/env node

const
    children = require('child_process'),
    bin = require('path').resolve(__dirname + '/../bin'),
    argv = process.argv.slice(2),
    params = '-jar ' + bin + '/raml-doc-standalone.jar' + (argv.length === 0 ? '' : (' ' + argv.join(' '))),
    proc = children.spawn('java', params.split(' '));

proc.stdout.on('data', function (data) {
    console.log(('' + data).substring(0, data.length - 1));
});
proc.stderr.on('data', function (data) {
    console.log(('' + data).substring(0, data.length - 1));
});

